vizhaal_data_management:
    resource: "@VizHAALDataManagementBundle/Resources/config/routing.yml"
    prefix:   /data

vizhaal_visplat:
    resource: "@VizHAALVisplatBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /administrator

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /administrator

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
