security:
    encoders:
        Enstb\Bundle\VisplatBundle\Entity\User: plaintext

    role_hierarchy:
        Administrator: [ROLE_SUPERADMIN]
        Doctor: [ROLE_USER, ROLE_ADMIN]
        Patient: ROLE_USER
        Family: ROLE_USER

    providers:
        main:
          entity: { class: Enstb\Bundle\VisplatBundle\Entity\User, property: username }
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: enstb_visplat_homepage
            logout:
                path:   /logout
                target: /login
            anonymous: true
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- The order are important, the first matched path is selected
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administrator, roles: [ROLE_ADMIN, ROLE_SUPERADMIN] }
        - { path: ^/data, roles: [ROLE_ADMIN, ROLE_SUPERADMIN] }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
