Enstb\Bundle\VisplatBundle\Entity\Roles:
    type: entity
    table: Roles
    id:
        Id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        Name:
            type: string
            length: 60
            unique: true
        Description:
            type: string
            length: 250
            unique: true
        DateCreated:
            type: datetime
    manyToMany:
        Users:
            targetEntity: Users
            joinTable:
                name: Users_Roles
                joinColumns:
                    UserId:
                        referencedColumnName: Id
                inverseJoinColumns:
                    RoleId:
                        referencedColumnName: Id
    lifecycleCallbacks:
        prePersist: [ setDateCreatedValue ]