enstb_visplat_homepage:
    pattern:  /
    defaults: { _controller: EnstbVisplatBundle:Visplat:status }

enstb_visplat_ajax_update_patient:
    pattern: /ajax/patient
    defaults: { _controller: EnstbVisplatBundle:Visplat:handleAjaxUpdate}
    options:
        expose: true

login:
    pattern:  /login
    defaults: { _controller: EnstbVisplatBundle:Visplat:login }

login_check:
    pattern:   /login_check

logout:
    pattern: /logout

